# rustfmt.toml
# https://rust-lang.github.io/rustfmt/?version=v1.6.0

edition = "2021"

# Control where to break lines
max_width = 110

# Control indentation style
hard_tabs = false
tab_spaces = 4

# Use or disable formatting
format_strings = true

# Control line endings
use_small_heuristics = "Max"

# Allow this method to go to a new line
allow_single_line_if_else = true

# # Control the wrapping of function parameters
# fn_params = "Brace"

# Prevent unnecessary `Ok` in results
force_explicit_unsafe = true

chain_split_single_line = true
chain_width = 30

array_width = 40
attr_fn_like_width = 40

fn_call_width = 40

binop_separator = "Front"

brace_style = "PreferSameLine"

condense_wildcard_suffixes = true

fn_single_line = true
struct_lit_single_line = true
struct_lit_width = 20

where_single_line = true

use_field_init_shorthand = true

force_multiline_blocks = true

format_code_in_doc_comments = true

imports_layout = "HorizontalVertical"

match_arm_leading_pipes = "Preserve"

merge_derives = true

imports_granularity = "Crate"

normalize_doc_attributes = true

group_imports = "StdExternalCrate"

spaces_around_ranges = true

# struct_field_align_threshold = 60

ignore = [
    "examples",
]
